spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.localtest.me:9000

server:
  port: 8081
logging:
  group:
    oauth: org.springframework.security.oauth2
    rest-template: org.springframework.web.client,org.springframework.http.client,org.apache.hc.client5.http

    security: org.springframework.security
    app: com.example
  level:
    oauth: trace
    rest-template: trace
    security: debug
    app: debug
