spring:
  security:
    oauth2:
      client:
        provider:
          spring-oauth-service:
            issuerUri: http://auth.localtest.me:9000
        registration:
          backend-client-credentials-client:
            provider: spring-oauth-service
            clientId: backend-client-credentials-client
            clientSecret: backend-client-credentials-client-secret
            authorizationGrantType: client_credentials
            scope:
              - openid
              - profile
              - resource.client_credentials_only
      resourceserver:
        jwt:
          issuer-uri: http://auth.localtest.me:9000

server:
  port: 8082
logging:
  group:
    oauth: org.springframework.security.oauth2
    rest-template: org.springframework.web.client,org.springframework.http.client,org.apache.hc.client5.http

    security: org.springframework.security
    app: com.example
  level:
    oauth: trace
    rest-template: trace
    security: debug
    app: debug
