spring:
  security:
    oauth2:
      client:
        provider:
          spring-oauth-service:
            issuerUri: http://auth.localtest.me:9000
        registration:
          hybrid-resource-server-oauth-client-service:
            provider: spring-oauth-service
            clientId: hybrid-resource-server-oauth-client-service
            clientSecret: hybrid-resource-server-oauth-client-service-secret
            authorizationGrantType: client_credentials
            scope:
              - openid
              - profile
              - resource.hybrid
      resourceserver:
        jwt:
          issuer-uri: http://auth.localtest.me:9000

server:
  port: 44444

logging:
  group:
    web-client: org.springframework.web.reactive.function.client,reactor.netty.http.client
    security: org.springframework.security, org.springframework.security.oauth2
    app: com.example
  level:
    web-client: trace
    security: debug
    app: debug
